config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/takahashi' => 'takahashi#yuuka'
  post '/takahashi' => 'takahashi#create'
  resources :books, :only => [:index, :show, :edit, :update, :destroy, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :introduction,length: { minimum: 2 }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
	end
	def show
		@ta = Book.find(params[:id])
	end

	def edit
	end
end

app/controllers/takahashi_controller.rb
class TakahashiController < ApplicationController
	def yuuka
		@nakamura = Book.new
		@aaa=Book.find(1)
	end
	def create
		yuta = Book.new(dmm_params)
		yuta.save
		redirect_to book_path(1)
	end
	def about
	end

	private
	def dmm_params
		params.require(:book).permit(:title,:introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/takahashi_helper.rb
module TakahashiHelper
end

app/views/books/show.html.erb
xxx

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/takahashi/yuuka.html.erb
<h1>テスト</h1>
<%= form_with model: @nakamura, url:'/takahashi' do |f| %>
  <%= f.text_field :title%>
  <%= f.text_field :introduction%>
  <%= f.submit %>
<% end %>
<%= link_to "詳細画面へ",books_path(@aaa)%>